# Cart Application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-app
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-app
  template:
    metadata:
      labels:
        app: cart-app
    spec:
      containers:
      - name: cart-app
        image: stutipatel8/learn:cartWebApp
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: DB_URL
          value: "cart-db"
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: cart-app
  namespace: microservices
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: cart-app
  type: LoadBalancer
---
# Cart Database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-db
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-db
  template:
    metadata:
      labels:
        app: cart-db
    spec:
      containers:
      - name: cart-db
        image: stutipatel8/learn:cartdb
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "200m"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root1234"
        - name: MYSQL_DATABASE
          value: "Cart_MKU"
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: cart-db-storage
      volumes:
      - name: cart-db-storage
        persistentVolumeClaim:
          claimName: cart-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cart-db
  namespace: microservices
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: cart-db
  type: ClusterIP
