# Order Application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-app
  template:
    metadata:
      labels:
        app: order-app
    spec:
      containers:
      - name: order-app
        image: stutipatel8/learn:orderWebApp
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: DB_URL
          value: "order-db"
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: order-app
  namespace: microservices
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: order-app
  type: LoadBalancer
---
# Order Database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-db
  template:
    metadata:
      labels:
        app: order-db
    spec:
      containers:
      - name: order-db
        image: stutipatel8/learn:orderdb
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "200m"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root1234"
        - name: MYSQL_DATABASE
          value: "Order_MKU"
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: order-db-storage
      volumes:
      - name: order-db-storage
        persistentVolumeClaim:
          claimName: order-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: order-db
  namespace: microservices
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: order-db
  type: ClusterIP
